kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "sonic-helm-chart.fullname" . }}
data:
  sonic.cfg: |-
    # Sonic
    # Fast, lightweight and schema-less search backend
    # Configuration file
    # Example: https://github.com/valeriansaliou/sonic/blob/master/config.cfg

    [server]

    log_level = "error"

    [channel]

    inet = "0.0.0.0:1491"
    tcp_timeout = 300

    auth_password = "SecretPassword"

    [channel.search]

    query_limit_default = 10
    query_limit_maximum = 100
    query_alternates_try = 4

    suggest_limit_default = 5
    suggest_limit_maximum = 20

    [store]

    [store.kv]

    path = "./data/store/kv/"

    retain_word_objects = 1000

    [store.kv.pool]

    inactive_after = 1800

    [store.kv.database]

    compress = true
    parallelism = 2
    max_files = 100
    max_compactions = 1
    max_flushes = 1

    [store.fst]

    path = "./data/store/fst/"

    [store.fst.pool]

    inactive_after = 300

    [store.fst.graph]


