[store.kv.database]
# Merge medium-sized memtables into medium L0 SSTs.
write_buffer_size = 16_384 # 16MiB
min_write_buffer_number_to_merge = 4 # L0 SST ≤ 64MiB
max_write_buffer_number = 64 # Do not stop writes while a flush is in progress (max 1GiB RAM usage).
