on:
  push:
    tags: ["v*.*.*"]
  # Support manually triggering a release without pushing a new tag after a
  # failed CI run (which required a CI fix).
  workflow_dispatch: {}

name: Build and release binary

jobs:
  make-release-github:
    name: Make GitHub release

    runs-on: ubuntu-24.04

    steps:
      # NOTE: Required by `WyriHaximus/github-action-get-previous-tag`…
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0
        with:
          pattern: v[0-9]* # NOTE: Flexible but ignores `core-*` and `server-*`.

      - name: Parse changelog
        run: |
          TAG='${{ steps.current_tag.outputs.tag }}'
          # Remove `v` prefix from `vX.Y.Z`.
          TAG="${TAG#v}"

          awk -f - server/CHANGELOG.md <<EOF > CHANGELOG.txt
          # Find the tag section header, and skip it.
          /^## \[?${TAG//\./\\.}\]?( |$)/              { in_section=1; next }

          # Skip the diff link definition.
          /^\[[^]]+\]: .+\/github.com\/.+\/compare\//  { next }

          # Skip all leading empty lines.
          in_section && !text_found && NF              { text_found=1 }

          # Stop if we reach next level 2 heading (other version).
          text_found && /^## /                         { exit }

          # Otherwise, print the line.
          text_found                                   { print }
          EOF

      - name: Release new version
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: ${{ steps.current_tag.outputs.tag }}
          name: Sonic ${{ steps.current_tag.outputs.tag }}
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-cargo:
    name: Publish to `cargo` registry (crates.io)

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Release package
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
        run: cargo publish -p sonic-server --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  build-publish-github:
    needs: make-release-github

    strategy:
      fail-fast: false
      matrix:
        include:
          - target_arch: x86_64
            target_platform: gnu
            target_triple: x86_64-unknown-linux-gnu
            container: debian:bookworm
          - target_arch: x86_64
            target_platform: rhel9
            target_triple: x86_64-unknown-linux-gnu
            container: redhat/ubi9
          - target_arch: x86_64
            target_platform: rhel10
            target_triple: x86_64-unknown-linux-gnu
            container: redhat/ubi10

    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.container }}

    name: ${{ matrix.target_arch }}-${{ matrix.target_platform }} (build + release)

    steps:
      - name: Install dependencies
        run: |
          case "${{ matrix.container }}" in
            redhat/ubi*)
              # `dtolnay/rust-toolchain` dependencies
              # NOTE: `curl-minimal` already installed by default.

              # `WyriHaximus/github-action-get-previous-tag` dependencies
              dnf install -y git

              # Sonic dependencies
              dnf install -y \
                gcc gcc-c++ make \
                clang clang-devel \
                libzstd-devel
              ;;
            *)
              apt-get update

              # `dtolnay/rust-toolchain` dependencies
              apt-get install -y curl

              # `WyriHaximus/github-action-get-previous-tag` dependencies
              apt-get install -y git

              # Sonic dependencies
              apt-get install -y \
                build-essential \
                clang libclang-dev llvm-dev \
                libzstd-dev
              ;;
          esac

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # FIX: Fix for <https://github.com/WyriHaximus/github-action-get-previous-tag/issues/81>.
          fetch-tags: true

      # FIX: Workaround for git error
      #   `fatal: detected dubious ownership in repository at '/__w/sonic/sonic'`.
      #   <https://github.com/actions/checkout>’s README says it’s the default
      #   but looks like there’s a bug when running .
      - name: Mark repository as safe in git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # NOTE: Running this before building to fail fast if an error arises.
      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0

      # NOTE: See <https://github.com/WyriHaximus/github-action-get-previous-tag/issues/81>,
      #   kept as a safety net in case bugs like this arise again.
      - name: Ensure current tag was found
        run: "[ '${{ steps.current_tag.outputs.tag }}' != '' ]"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master on 2026-05-14
        with:
          toolchain: stable

      - name: Verify versions
        run: |
          rustc --version
          rustup --version 2>/dev/null
          cargo --version
          gcc --version
          clang --version

      - id: build_archive
        name: Build and archive binary
        run: ./scripts/build_release_archive.sh ${{ matrix.target_arch }} ${{ matrix.target_platform }} ${{ matrix.target_triple }}

      - name: Publish archive in GitHub release
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: ${{ steps.current_tag.outputs.tag }}
          files: ${{ steps.build_archive.outputs.archive_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-publish-packagecloud:
    name: Build and publish to Packagecloud
    needs: build-publish-github
    # Always run, no matter the outcome of `build-publish-github`.
    # The reason we need this is because if compilation failed for one platform
    # not supported in our Packagecloud release, we should still try to publish
    # to Packagecloud. If required builds failed, it will be caught anyway.
    if: always()

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build packages
        run: ./scripts/build_packages.sh

      # FIX: Fixes `dpkg-parsechangelog: error: cannot open file debian/changelog: No such file or directory`.
      - name: Link `debian` to `packaging/debian`
        run: ln -s packaging/debian debian

      - name: Push packages to Packagecloud
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
        uses: faucetsdn/action-packagecloud-upload-debian-packages@89b1e7201d7f9df94e3f360d9cb77134dd5ffc05 # v1
        with:
          path: ./packages
          repo: ${{ secrets.PACKAGECLOUD_REPO }}
          token: ${{ secrets.PACKAGECLOUD_TOKEN }}

  build-publish-docker:
    name: Build and publish to Docker Hub

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Acquire Docker image metadata
        id: metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: valeriansaliou/sonic

      - name: Login to Docker Hub
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # 4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # 4.1.0

      - name: Build and push Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        id: build
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_type == 'tag' || github.ref == 'refs/heads/master' }}
