on:
  push:
    tags:
      - "core-v*.*.*"

name: Release library

jobs:
  cargo-publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master on 2026-05-14
        with:
          toolchain: stable

      - name: Verify versions
        run: |-
          rustc --version
          rustup --version 2>/dev/null
          cargo --version

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0

      - name: Release package
        run: cargo publish -p sonic-core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

      - name: Parse tag name
        id: parsing
        run: |
          # Parse tag 'core-vX.Y.Z' into 'vX.Y.Z'.
          TAG='${{ steps.current_tag.outputs.tag }}'
          echo "version=${TAG#core-}" >> $GITHUB_OUTPUT

      - name: Parse changelog
        run: |
          TAG='${{ steps.parsing.outputs.version }}'
          # Remove `v` prefix from `vX.Y.Z`.
          TAG="${TAG#v}"

          awk -f - core/CHANGELOG.md <<EOF > CHANGELOG.txt
          # Find the tag section header, and skip it.
          /^## \[?${TAG//\./\\.}\]?( |$)/              { in_section=1; next }

          # Skip the diff link definition.
          /^\[[^]]+\]: .+\/github.com\/.+\/compare\//  { next }

          # Skip all leading empty lines.
          in_section && !text_found && NF              { text_found=1 }

          # Stop if we reach next level 2 heading (other version).
          text_found && /^## /                         { exit }

          # Otherwise, print the line.
          text_found                                   { print }
          EOF

      - name: Release new version
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: ${{ steps.current_tag.outputs.tag }}
          name: Sonic core ${{ steps.parsing.outputs.version }}
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
